# Generated by Django 5.1.7 on 2025-11-03 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_following'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='following',
            constraint=models.UniqueConstraint(fields=('source', 'target'), name='unique_follow_pair'),
        ),
    ]
